# Generated by Django 4.2.6 on 2024-04-23 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
