# Generated by Django 4.2.6 on 2024-05-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exercise_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Shoulder', 'Shoulder'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('Flat barbell bench press', 'Flat barbell bench press'), ('Incline barbell bench press', 'Incline barbell bench press'), ('flat dumbbell Bench Press', 'flat dumbbell Bench Press'), ('Incline dumbbell press low angle', 'Incline dumbbell press low angle'), ('Incline dumbbell press high angle', 'Incline dumbbell press high angle'), ('Dumbbell flyes', 'Dumbbell flyes'), ('Cable flyes', 'Cable flyes'), ('Machine flyes', 'Machine flyes'), ('Machine Chest Press', 'Machine Chest Press'), ('Dumbbell shoulder press', 'Dumbbell shoulder press'), ('Barbell Dumbbell press', 'Barbell Dumbbell press'), ('Cable lateral raises', 'Cable lateral raises'), ('Dumbbell lateral raises', 'Dumbbell lateral raises'), ('Dumbbell Front Raises', 'Dumbbell Front Raises'), ('Cable Front Raises', 'Cable Front Raises'), ('Front Raises', 'Front Raises'), ('Rear Delt Machine', 'Rear Delt Machine'), ('Rear Delt Dumbbell', 'Rear Delt Dumbbell'), ('Machine shoulder press', 'Machine shoulder press'), ('Barbell Bent over row', 'Barbell Bent over row'), ('Rope Pulldown', 'Rope Pulldown'), ('Deadlift', 'Deadlift'), ('Lat pulldown straight bar', 'Lat pulldown straight bar'), ('Lat pulldown close grip', 'Lat pulldown close grip'), ('Cable row wide', 'Cable row wide'), ('Cable row narrow', 'Cable row narrow'), ('Single arm lat pulldown', 'Single arm lat pulldown'), ('Machine Row', 'Machine Row'), ('pull ups', 'pull ups'), ('Squats', 'Squats'), ('Leg press', 'Leg press'), ('Leg extension', 'Leg extension'), ('Leg curls', 'Leg curls'), ('Bulgarian split squats', 'Bulgarian split squats'), ('Romian deadlift', 'Romian deadlift'), ('Bicep curls', 'Bicep curls'), ('Hamemr curls', 'Hamemr curls'), ('Cable bicep curls', 'Cable bicep curls'), ('Cable hammer curl', 'Cable hammer curl'), ('Cable tricep extension', 'Cable tricep extension'), ('Bar tricep extension', 'Bar tricep extension'), ('Overhead extension', 'Overhead extension'), ('Dips', 'Dips')], max_length=50),
        ),
    ]
